# Microsoft Windows ini File
#
# Name: DesktopInfo Configuration
# Version: 0.5.0.0
# Date: 2020-03-18
# Author: MMillar
# https://github.com/mmillar-bolis
# http://www.bolis.com
#
# Description:
# This is the configuration file read by `DesktopInfo.exe`
#
# Credits:
# Glenn Delahoy - http://www.glenn.delahoy.com/software/
#

[options]
top=15

[pages]
1=Main

[items]

# page 9 - test
PAGE=1
COMMENT=style:bu,text:Computer Information

# Host information
HOST=text:Device Name,display:%1
USER=set:username,hidden:0
NETWORKINTERFACES=interval:30,operstatus:1,iftype:6 71,row-text:IP Address (%2) ,display:%8
UPTIME=interval:60,display:%1 days %2 hrs %3 mins
